# Generated by Django 3.2.4 on 2021-07-17 21:36

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('receive_promotions', models.BooleanField(default=False)),
                ('status', models.CharField(default='1', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('card_name', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True))),
                ('card_num', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=16, null=True))),
                ('card_exp', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=5, null=True))),
                ('card_code', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=3, null=True))),
            ],
        ),
    ]
