# Generated by Django 3.2.4 on 2021-07-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orig_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
