# Generated by Django 3.2.4 on 2021-07-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20210720_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
