# Generated by Django 3.2.4 on 2021-07-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_user_promos_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
