# Generated by Django 3.2.4 on 2021-07-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20210718_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=2),
        ),
    ]
