# Generated by Django 3.2.4 on 2021-07-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_promotion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promos_used',
            field=models.CharField(default='', max_length=200),
        ),
    ]
